### ISSUE TITLE
Any updated methods for this?

### ISSUE THREAD

**Issue by liamxg** [saws-lab/SAP_H3N2_ML#5]
Dear @saws-lab,

Could I know any updated method for this, thanks.

**Comment by saws-lab** [comment]
Hi @liamxg. If you are asking about the ML model for seasonal antigenic prediction, the current version with the AdaBoost model is the most updated one. Otherwise, kindly provide more details about the query.

**Comment by liamxg** [comment]
Dear @saws-lab,

Thanks for your reply.  Could this be used for SC2?

**Comment by saws-lab** [comment]
This ML model is specifically optimized and trained for influenza A H3N2, however, the provided codes could be used to optimize and train the model for SC2 using relevant data.

**Comment by liamxg** [comment]
Dear @saws-lab,
Would you like to cooperate with me for SC2?

**Comment by feinianyu0218** [comment]
Hello, could you provide the training and testing data for the model，such as sequences of virus-antiserum, as well as data on virus affinity and antiserum potency.thank you !

**Comment by saws-lab** [comment]
Sure, let's discuss this further over email (awais.shah@unimelb.edu.au). I am closing this issue.
