### ISSUE TITLE
 could you provide the training and testing data for the model?

### ISSUE THREAD

**Issue by feinianyu0218** [saws-lab/SAP_H3N2_ML#6]
such as sequences of virus-antiserum, as well as data on virus affinity and antiserum potency.

**Comment by saws-lab** [comment]
Thank you for reviewing our work and bringing this to our attention. The dataset is included with the published paper [here](https://doi.org/10.1038/s41467-024-47862-9) (see Supplementary Data 1). It outlines the specific HI data from the [Crick Worldwide Influenza Centre reports](https://www.crick.ac.uk/research/platforms-and-facilities/worldwide-influenza-centre/annual-and-interim-reports) and the HA protein sequences from [GISAID](https://gisaid.org/) and [IVR](https://www.ncbi.nlm.nih.gov/genomes/FLU/Database/nph-select.cgi?go=database). This data can be used to build the training and test sets using the provided source codes. The model further estimates virus avidity and antiserum potency based on name and passage information available in Supplementary Data 1.

**Comment by feinianyu0218** [comment]
Thank you for your response. However, in the `Supp_Fig2a_seasonal_data_distribution.ipynb`, the `data_fn` is set to `nhts_ha1_binary.csv`, and the `dist_fn` is `SuppFig2a_seasonal_data_distribution.csv`. Since Supplementary Data 1 contains only one file, which dataset should be inputted from either `data_fn` or `dist_fn`?

**Comment by feinianyu0218** [comment]
Thank you for your response. However, in the `Supp_Fig2a_seasonal_data_distribution.ipynb`, the `data_fn` is set to `nhts_ha1_binary.csv`, and the `dist_fn` is `SuppFig2a_seasonal_data_distribution.csv`. Since Supplementary Data 1 contains only one file, which dataset should be inputted from either `data_fn` or `dist_fn`? Additionally, I did not see the HA sequences or specific HI data in Supplementary Data 1.

**Comment by feinianyu0218** [comment]
Thank you for your reply, and I apologize for the previous question. However, when I ran the program using Supplementary Data 1, it indicated that the "nht" metric was missing. I checked Supplementary Data 1, but it doesn't contain the "nht" values either. Could you please provide data that includes the "nht" values?

**Comment by saws-lab** [comment]
Thank you for bringing this to our attention. The NHT values can be computed using the equation provided in the subsection "Antigenic and Genetic Datasets of IAV H3N2" under the "Methods" section. You can derive these values from the HI titer data found in the Crick reports, as referenced in the "Source" column of Supplementary Data 1. Unfortunately, we are unable to provide the NHT values directly due to restrictions from source data providers.

**Comment by feinianyu0218** [comment]
thank you for the response
